apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: github-deployment-test
  title: New Github  Repo
  description: Create a New github Repo
  tags:
    - recommended
    - react
spec:
  owner: user:guest
  type: service
  parameters:
    - title: Provide some simple information
      required:
        - repo_name
        - description
        - admin
      properties:
        repo_name:
          title: Name
          type: string
          description: Name of the github repo
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Description for the Github repo
        admin:
          title: Admin
          type: string
          description: Comma seperate list of Admins
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
